name: Cypress Test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress Run
        uses: cypress-io/github-action@v6

  cypress-mobile-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
      - name: Cypress Run on Mobile
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:mobile